/* INSERT QUERY */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (4, 'Mephisto', 'Assassin', 'Diablo', 'Medium', 'enslave humanity.', 'Skull Missile', 'Lightning Nova', 'Shade of Mephisto', 'Consume Souls', 'Durance of Hate', 'Lord of Hatred', 'Mephisto.jpg', 'Lord of Hatred');
/* Entry 2 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (1, 'Imperius', 'Warrior', 'Diablo', 'Medium', 'Leader of the Angiris Council and Aspect of Valor, Imperius has valiantly led the armies of the High Heavens to innumerous victories over the demons of the Burning Hells.', 'Celestial Charge', 'Solarions Fire', 'Molten Armor', 'Angelic Armaments', 'Wrath of the Angiris', 'Valorous', 'Imperius.jpg', 'Archangel of Valor');
/* Entry 3 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (2, 'Orphea', 'Assassin', 'Nexus', 'Medium', 'Rejecting the dark power her father had begun to consort with, Orphea tried to run away from the Raven Lords influence. But after witnessing Kings Crest fall to his machinations, she was convinced she needed to stand and fight.', 'Shadow Waltz', 'Chomp', 'Dread', 'Eternal Feast', 'Crushing Jaws', 'Overflowing Chaos', 'Orphea.jpg', 'Heir of Raven Court');
/* Entry 4 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (3, 'MalGanis', 'Warrior', 'Warcraft', 'Medium', 'Cunning and intelligent, MalGanis was chosen to bring Arthas Menethil into the Lich Kings service. After manipulating the prince into purging Stratholme of life, he finally fell to Frostmourne as Arthas first act.', 'Fel Claws', 'Necrotic Embrace', 'Night Rush', 'Carrion Swarm', 'Dark Conversion', 'Vampiric Touch', 'Malganis.jpg', 'Nathrezim Lord');
/* Entry 5 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (5, 'Whitemane', 'Support', 'Warcraft', 'Medium', 'As the High Inquisitor of the Scarlet Crusade, Sally Whitemane zealously leads her champions in a neverending war against the undead. Under her guiding Light, all who have been touched by the plague of death.', 'Desperate Plea', 'Inquisition', 'Searing Lash', 'Scarlet Aegis', 'Divine Reckoning', 'Zeal', 'Whitemane.jpg', 'High Inquisitor');
/* Entry 6 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (6, 'Yrel', 'Warrior', 'Warcraft', 'Medium', 'After traveling to an Alternate Draenor, the forces of Azeroth saved the acolyte Yrel from the Iron Horde. With their aid, she rose to the rank of Exarch and fought back the demonic invasion of her world. ', 'Vindication', 'Righteous Hammer', 'Avenging Wrath', 'Ardent Defender', 'Sacred Ground', 'Divine Purpose', 'Yrel.jpg', 'Light of Hope');
/* INSERT QUERY NO: 7 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (7, 'Deckard', 'Support', 'Diablo', 'Medium', 'As an avid scholar, Deckard Cain has dedicated his life to the pursuit of knowledge. He has been an advisor, storyteller, and friend to Sanctuarys greatest heroes, guiding them through peril time and again.', 'Healing Potion', 'Horadric Cube', 'Scroll of Sealing', 'Stay Awhile and Listen', 'Lorendo', 'Fortitude of the Faithful', 'Deckard.jpg', 'The last Horadrim');
/* INSERT QUERY NO: 8 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (8, 'Fenix', 'Assassin', 'StarCraft', 'Medium', 'As one of the greatest heroes in protoss history, Fenixs deeds on the battlefield are legendary. After falling to the zerg during the invasion of Aiur, his body was recovered and implanted into a dragoon.', 'Plasma Cutter', 'Weapon Mode', 'Warp', 'Purification Salvo', 'Planet Cracker', 'Shield Capacitor', 'Fenix.jpg', 'Steward of the Templar');
/* INSERT QUERY NO: 9 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (9, 'Maiev', 'Assassin', 'Warcraft', 'Hard', 'Maiev Shadowsong stood watch over the imprisoned Betrayer for ten thousand years, and hunted him relentlessly after he was released. Some say shes determined; others say shes obsessed.', 'Fan of Knives', 'Umbral Bind', 'Spirit of Vengeance', 'Containment Disc', 'Wardens Cage', 'Vault of the Wardens', 'Maiev.jpg', 'The Warden');
/* INSERT QUERY NO: 10 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (10, 'Blaze', 'Warrior', 'StarCraft', 'Medium', 'Cpl. Miles Blaze Lewis has always been drawn to the flame, but it wasnt until he joined up with Raynors Raiders that he put his pyromania to good use. Hes seen his fair share of battles since then.', 'Flame Stream', 'Oil Spill', 'Jet Propulsion', 'Bunker Drop', 'Combustion', 'Pyromania', 'Blaze.jpg', 'Veteran Firebat');
/* INSERT QUERY NO: 11 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (11, 'Hanzo', 'Assassin', 'Overwatch', 'Medium', 'Once heir to the Shimada clans criminal empire, Hanzo abandoned his birthright after he almost killed his younger brother. He now strives to perfect his skills as a warrior and sees the Nexus and its endless conflict as the ideal training ground.', 'Storm Bow', 'Scatter Arrow', 'Sonic Arrow', 'Dragonstrike', 'Dragons Arrow', 'Natural Agility', 'Hanzo.jpg', 'Master Assassin');
/* INSERT QUERY NO: 12 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (12, 'Alexstrasza', 'Support', 'Warcraft', 'Medium', 'Alexstrasza, the queen of dragons, was empowered by the titans to be the guardian of all life on Azeroth. She has aided mortals time and again, even at great personal cost.', 'Gift of Life', 'Abundance', 'Flame Buffet', 'Lifebender', 'Cleansing FLame', 'Dragonqueen', 'Alexstrasza.jpg', 'The Life-Binder');
/* INSERT QUERY NO: 13 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (13, 'Junkrat', 'Assassin', 'Overwatch', 'Medium', 'The destruction of the Australian omnium left the area an irradiated waste and survivors like Jamison Fawkes were greatly affected by radiation. Now as the explosive-obsessed criminal Junkrat, he is renowned for leaving havoc and bedlam in his wake.', 'Frag Launcher', 'Concussion Mine', 'Steel Trap', 'Rip-tire', 'Rocket Ride', 'Total Mayhem', 'Junkrat.jpg', 'Junker Demolitionist');
/* INSERT QUERY NO: 14 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (14, 'Ana', 'Support', 'Overwatch', 'Hard', 'As a founding member of Overwatch and one of the worlds best snipers, Ana Amari uses her skills to protect the innocent. Though she went MIA after losing her eye.', 'Healing Dart', 'Biotic Grenade', 'Sleep Dart', 'Nano Boost', 'Eye of Horus', 'Shrike', 'Ana.jpg', 'Veteran Sniper');
/* INSERT QUERY NO: 15 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (15, 'KelThuzad', 'Assassin', 'Warcraft', 'Hard', 'KelThuzad has faithfully served the Lich King both in life and after death. Reanimated as the Archlich of the Scourge and given domain of the Dread Necropolis, KelThuzad remains Arthas most trusted advisor and master of the cold dark.', 'Death and Decay', 'Frost Nova', 'Chains of KelThuzad', 'Frost Blast', 'Shadow Fissure', 'Master of the Cold Dark', 'Kelthuzad.jpg', 'Archlich of Naxxramas');
/* INSERT QUERY NO: 16 */
INSERT INTO HERO(heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (16, 'Garrosh', 'Warrior', 'Warcraft', 'Medium', 'As the new warchief of the Horde, Garrosh is a proud and vicious warrior who rules with an iron fist. His hatred for the Alliance burns like wildfire, and he will stop at nothing to destroy them. By his axe, the orcs will reclaim their rightful glory.', 'Groundbreaker', 'Bloodthirst', 'Wrecking Ball', 'Warlords Challenge', 'Decimate', 'Armor Up', 'Garrosh.jpg', 'Son of Hellscream');
