INSERT INTO USER (userID, username, password, admin) VALUES (1, "admin", "admin", true);
INSERT INTO USER (userID, username, password, admin) VALUES (2, "user1", "user1", false);

/* INSERT QUERY */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (1, 'Nightmayr', 'Chad', 'Earth', 'Extreme', 'Formally known as Umayr, Nightmayr pummels his enemies.', 'Git BASH!', 'Throw a chicken', 'Plank', 'Rip Shirt', 'Start a fight', 'Being a Chad', 'Nightmayr.jpg', 'Umayr by day, nightmayr by night.');

INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (4, 'Mephisto', 'Assassin', 'Diablo', 'Medium', 'enslave humanity.', 'Skull Missile', 'Lightning Nova', 'Shade of Mephisto', 'Consume Souls', 'Durance of Hate', 'Lord of Hatred', 'Mephisto.jpg', 'Lord of Hatred');
/* Entry 2 *//* Entry 3 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (2, 'Orphea', 'Assassin', 'Nexus', 'Medium', 'Rejecting the dark power her father had begun to consort with, Orphea tried to run away from the Raven Lords influence. But after witnessing Kings Crest fall to his machinations, she was convinced she needed to stand and fight.', 'Shadow Waltz', 'Chomp', 'Dread', 'Eternal Feast', 'Crushing Jaws', 'Overflowing Chaos', 'Orphea.jpg', 'Heir of Raven Court');
/* Entry 4 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (3, 'MalGanis', 'Warrior', 'Warcraft', 'Medium', 'Cunning and intelligent, MalGanis was chosen to bring Arthas Menethil into the Lich Kings service. After manipulating the prince into purging Stratholme of life, he finally fell to Frostmourne as Arthas first act.', 'Fel Claws', 'Necrotic Embrace', 'Night Rush', 'Carrion Swarm', 'Dark Conversion', 'Vampiric Touch', 'Malganis.jpg', 'Nathrezim Lord');
/* Entry 5 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (5, 'Whitemane', 'Support', 'Warcraft', 'Medium', 'As the High Inquisitor of the Scarlet Crusade, Sally Whitemane zealously leads her champions in a neverending war against the undead. Under her guiding Light, all who have been touched by the plague of death.', 'Desperate Plea', 'Inquisition', 'Searing Lash', 'Scarlet Aegis', 'Divine Reckoning', 'Zeal', 'Whitemane.jpg', 'High Inquisitor');
/* Entry 6 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (6, 'Yrel', 'Warrior', 'Warcraft', 'Medium', 'After traveling to an Alternate Draenor, the forces of Azeroth saved the acolyte Yrel from the Iron Horde. With their aid, she rose to the rank of Exarch and fought back the demonic invasion of her world. ', 'Vindication', 'Righteous Hammer', 'Avenging Wrath', 'Ardent Defender', 'Sacred Ground', 'Divine Purpose', 'Yrel.jpg', 'Light of Hope');
/* INSERT QUERY NO: 7 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (7, 'Deckard', 'Support', 'Diablo', 'Medium', 'As an avid scholar, Deckard Cain has dedicated his life to the pursuit of knowledge. He has been an advisor, storyteller, and friend to Sanctuarys greatest heroes, guiding them through peril time and again.', 'Healing Potion', 'Horadric Cube', 'Scroll of Sealing', 'Stay Awhile and Listen', 'Lorendo', 'Fortitude of the Faithful', 'Deckard.jpg', 'The last Horadrim');
/* INSERT QUERY NO: 8 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (8, 'Fenix', 'Assassin', 'StarCraft', 'Medium', 'As one of the greatest heroes in protoss history, Fenixs deeds on the battlefield are legendary. After falling to the zerg during the invasion of Aiur, his body was recovered and implanted into a dragoon.', 'Plasma Cutter', 'Weapon Mode', 'Warp', 'Purification Salvo', 'Planet Cracker', 'Shield Capacitor', 'Fenix.jpg', 'Steward of the Templar');
/* INSERT QUERY NO: 9 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (9, 'Maiev', 'Assassin', 'Warcraft', 'Hard', 'Maiev Shadowsong stood watch over the imprisoned Betrayer for ten thousand years, and hunted him relentlessly after he was released. Some say shes determined; others say shes obsessed.', 'Fan of Knives', 'Umbral Bind', 'Spirit of Vengeance', 'Containment Disc', 'Wardens Cage', 'Vault of the Wardens', 'Maiev.jpg', 'The Warden');
/* INSERT QUERY NO: 10 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (10, 'Blaze', 'Warrior', 'StarCraft', 'Medium', 'Cpl. Miles Blaze Lewis has always been drawn to the flame, but it wasnt until he joined up with Raynors Raiders that he put his pyromania to good use. Hes seen his fair share of battles since then.', 'Flame Stream', 'Oil Spill', 'Jet Propulsion', 'Bunker Drop', 'Combustion', 'Pyromania', 'Blaze.jpg', 'Veteran Firebat');
/* INSERT QUERY NO: 11 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (11, 'Hanzo', 'Assassin', 'Overwatch', 'Medium', 'Once heir to the Shimada clans criminal empire, Hanzo abandoned his birthright after he almost killed his younger brother. He now strives to perfect his skills as a warrior and sees the Nexus and its endless conflict as the ideal training ground.', 'Storm Bow', 'Scatter Arrow', 'Sonic Arrow', 'Dragonstrike', 'Dragons Arrow', 'Natural Agility', 'Hanzo.jpg', 'Master Assassin');
/* INSERT QUERY NO: 12 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (12, 'Alexstrasza', 'Support', 'Warcraft', 'Medium', 'Alexstrasza, the queen of dragons, was empowered by the titans to be the guardian of all life on Azeroth. She has aided mortals time and again, even at great personal cost.', 'Gift of Life', 'Abundance', 'Flame Buffet', 'Lifebender', 'Cleansing FLame', 'Dragonqueen', 'Alexstrasza.jpg', 'The Life-Binder');
/* INSERT QUERY NO: 13 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (13, 'Junkrat', 'Assassin', 'Overwatch', 'Medium', 'The destruction of the Australian omnium left the area an irradiated waste and survivors like Jamison Fawkes were greatly affected by radiation. Now as the explosive-obsessed criminal Junkrat, he is renowned for leaving havoc and bedlam in his wake.', 'Frag Launcher', 'Concussion Mine', 'Steel Trap', 'Rip-tire', 'Rocket Ride', 'Total Mayhem', 'Junkrat.jpg', 'Junker Demolitionist');
/* INSERT QUERY NO: 14 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (14, 'Ana', 'Support', 'Overwatch', 'Hard', 'As a founding member of Overwatch and one of the worlds best snipers, Ana Amari uses her skills to protect the innocent. Though she went MIA after losing her eye.', 'Healing Dart', 'Biotic Grenade', 'Sleep Dart', 'Nano Boost', 'Eye of Horus', 'Shrike', 'Ana.jpg', 'Veteran Sniper');
/* INSERT QUERY NO: 15 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (15, 'KelThuzad', 'Assassin', 'Warcraft', 'Hard', 'KelThuzad has faithfully served the Lich King both in life and after death. Reanimated as the Archlich of the Scourge and given domain of the Dread Necropolis, KelThuzad remains Arthas most trusted advisor and master of the cold dark.', 'Death and Decay', 'Frost Nova', 'Chains of KelThuzad', 'Frost Blast', 'Shadow Fissure', 'Master of the Cold Dark', 'Kelthuzad.jpg', 'Archlich of Naxxramas');
/* INSERT QUERY NO: 16 */
INSERT INTO HERO(heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (16, 'Garrosh', 'Warrior', 'Warcraft', 'Medium', 'As the new warchief of the Horde, Garrosh is a proud and vicious warrior who rules with an iron fist. His hatred for the Alliance burns like wildfire, and he will stop at nothing to destroy them. By his axe, the orcs will reclaim their rightful glory.', 'Groundbreaker', 'Bloodthirst', 'Wrecking Ball', 'Warlords Challenge', 'Decimate', 'Armor Up', 'Garrosh.jpg', 'Son of Hellscream');
/* INSERT QUERY NO: 17 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (17, 'Stukov', 'Support', 'StarCraft', 'Medium', 'Alexei Stukov had a hard life, and an even harder death. He has been betrayed, shot into space, resurrected and infested, almost cured, and then experimented upon as the infestation returned.', 'Healing Pathogen', 'Weighted Pustule', 'Lurking Arm', 'Flailing Swipe', 'Massive Shove', 'Bio-kill Switch', 'Stukov.jpg', 'Infested Admiral');
/* INSERT QUERY NO: 18 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (18, 'Malthael', 'Assassin', 'Diablo', 'Medium', 'Once the Aspect of Wisdom, Malthael abandoned heaven after the Worldstones destruction. In secret, he had resolved to end the Eternal Conflict by becoming a Reaper of Souls and eliminating everything affected by demonic corruption, including humanity.', 'Soul Rip', 'Wraith Strike', 'Death Shroud', 'Tormented Souls', 'Last Rites', 'Reapers Mark', 'Malthael.jpg', 'Aspect of Death');
/* INSERT QUERY NO: 19 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (19, 'D.Va', 'Warrior', 'Overwatch', 'Medium', 'Hana Song is both a world champion professional gamer and a burgeoning global icon. As a member of South Koreas elite MEKA unit, she fights to protect her homeland from the colossal omnic threat lurking within the East China Sea."', 'Boosters', 'Defense Matrix', 'Self-destruct', 'Bunny Hop', 'Big Shot', 'Mech Mode', 'Dva.jpg', 'Meka Pilot');
/* INSERT QUERY NO: 20 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (20, 'Genji', 'Assassin', 'Overwatch', 'Hard', 'Once the carefree youngest scion of the Shimada clan, Genji was cut down by his own brother for refusing to take part in their illegal ventures. Grafted into a cyborg body by Overwatch, Genji walks his own path as one who fights for whats right.', 'Shuriken', 'Deflect', 'Swift Strike', 'Dragonblade', 'X-Strike', 'Cyber Agility', 'Genji.jpg', 'Cybernetic Ninja');
/* INSERT QUERY NO: 21 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (21, 'Cassia', 'Assassin', 'Diablo', 'Medium', 'After shattering the Worldstone, the young Amazon Cassia had changed. She had seen hatred and destruction firsthand. If the Askari were to survive the coming darkness, they needed an army. She would begin their training immediately.', 'Lightning Fury', 'Blinding Light', 'Fend', 'Ball Lightning', 'Valkyrie', 'Avoidance', 'Cassia.jpg', 'Amazon Warmatron');
/* INSERT QUERY NO: 22 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (22, 'Probius', 'Specialist', 'StarCraft', 'Hard', 'Since his activation, Probius has always wanted to prove himself. He may be small, but he made a big difference by warping in a critical pylon during the retaking of Aiur. As the bravest of probes, Probius is eager to fulfill his purpose in the Nexus.', 'Disuption Pulse', 'Warp Rift', 'Photon Cannon', 'Pylon Overcharge', 'Null Gate', 'Warp in Pylon', 'Probius.jpg', 'Curious Probe');
/* INSERT QUERY NO: 23 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (23, 'Lúcio', 'Support', 'Overwatch', 'Medium', 'From the streets of Rio to the clubs on Kings Row, Lúcios beats bring the party to life and drive the people to action. Now hes on tour in the Nexus, ready to break it down and to continue fighting for whats right.', 'Soundwave', 'Crossfade', 'Amp it up', 'Sound Barrier', 'Reverse Amp', 'Wall Ride', 'Lucio.jpg', 'Freedom Fighting DJ');
/* INSERT QUERY NO: 24 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (24, 'Valeera', 'Assassin', 'Warcraft', 'Hard', 'For a time, the gladiator Valeera Sanguinar served dutifully as one of Varian Wrynns personal bodyguards. Now her shadowy skills find her a natural fit within the secretive rogue order, the Uncrowned, in their fight against the Legion.', 'Sinister Strike', 'Blade Flurry', 'Eviscerate', 'Smoke Bomb', 'Cloak of Shadows', 'Vanish', 'Valeera.jpg', 'Shadow of the Uncrowned');
/* INSERT QUERY NO: 25 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (25, 'Zuljin', 'Assassin', 'Warcraft', 'Medium', 'Before the elves and their Alliance, the forests of Lordaeron belonged to the trolls of the Amani empire. As their warlord, Zuljin has united the tribes into an army that stands ready to take back what is theirs.', 'Grievous Throw', 'Twin Cleave', 'Regeneration', 'Tazdingo!', 'Guillotine', 'Berseker', 'Zuljin.jpg', 'Warlord of the Amani');
/* INSERT QUERY NO: 26 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (26, 'Ragnaros', 'Assassin', 'Warcraft', 'Medium', 'As the lord of Azeroths fire elementals, Ragnaros desires nothing more than to burn the world to ash. Banished to the Firelands eons ago, the Firelord now turns his rage toward the Nexus, intent on incinerating everything and everyone within it.', 'Empower Sulfuras', 'Living Meteor', 'Blast Wave', 'Sulfuras Smash', 'Lava Wave', 'Molten Core', 'Ragnaros.jpg', 'The Firelord');
/* INSERT QUERY NO: 27 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (27, 'Varian', 'Multiclass', 'Warcraft', 'Medium', 'Few would have expected that the gladiator known only as LoGosh was in truth the missing ruler of Stormwind, Varian Wrynn. Now the High King of the Alliance, his every action shapes the destiny of Azeroth itself.', 'Lions Fang', 'Parry', 'Charge', 'Taunt', 'Twin Blades of Fury', 'Heroic Strike', 'Varian.jpg', 'High King of the Alliance');
/* INSERT QUERY NO: 28 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (28, 'Samuro', 'Assassin', 'Warcraft', 'Hard', 'The last remaining blademaster to wear the banner of the Burning Blade, is on a warriors pilgrimage in search of vengeance and redemption for his fallen clan. It will be a long journey, but he has sworn an oath to restore his clans honor.', 'Mirror Image', 'Critical Strike', 'Wind Walk', 'Bladestorm', 'Illusion Master', 'Image Transmission', 'Samuro.jpg', 'The Blademaster');
/* INSERT QUERY NO: 29 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (29, 'Zarya', 'Warrior', 'Overwatch', 'Easy', 'Aleksandra Zaryanova is one of the worlds strongest women and was a promising athlete, but all that changed when the Siberian omnium reawakened. As a soldier in the Russian Defense Force, she now proudly uses her strength to protect the ones she loves.', 'Particle Grenade', 'Personal Barrier', 'Shield Ally', 'Graviton Surge', 'Expulsion Zone', 'Energy', 'Zarya.jpg', 'Defense of Russia');
/* INSERT QUERY NO: 30 */
INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (30, 'Alarak', 'Assassin', 'StarCraft', 'Hard', 'Not all heroes are born of altruism... some, like Alarak, simply desire vengeance. As the new Highlord of the Taldarim, Alarak leads his people to a destiny free of the corrupt influence of the fallen xelnaga.', 'Discord Strike', 'Telekinesis', 'Lightning Surge', 'Deadly Charge', 'Counter-strike', 'Sadism', 'Alarak.jpg', 'Highlord of the TalDarim');

INSERT INTO HERO (heroID, name, heroClass, universe, difficulty, description, basic1, basic2, basic3, ult1, ult2, trait, image, tag) VALUES (31, 'Imperius', 'Warrior', 'Diablo', 'Medium', 'Leader of the Angiris Council and Aspect of Valor, Imperius has valiantly led the armies of the High Heavens to innumerous victories over the demons of the Burning Hells.', 'Celestial Charge', 'Solarions Fire', 'Molten Armor', 'Angelic Armaments', 'Wrath of the Angiris', 'Valorous', 'Imperius.jpg', 'Archangel of Valor');